-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgdi4sXeYI2SaznWG7
g4x7l6EFFTesLTifXQl4c1YesN2gCgYIKoZIzj0DAQehRANCAAQC42hKlZwzaOFd
gMJo5mkWtTImbHXRrialllNmCwFM4UzQKhsjNiICJHs1js+W40PqF3MwReSy6oyk
5QcUEY7u
-----END PRIVATE KEY-----